// africaCountries.ts

export interface LGAData {
  name: string;
}

export interface Subdivision {
  name: string; // State / Province / Region / Governorate
  lgas?: LGAData[]; // Optional — populated for Nigeria
}

export interface Country {
  country: string;
  subdivisions: Subdivision[];
}

export const africaCountries: Country[] = [
  {
    country: "Nigeria",
    subdivisions: [
      {
        name: "Abia",
        lgas: [
          { name: "Aba North" },
          { name: "Aba South" },
          { name: "Arochukwu" },
          { name: "Bende" },
          { name: "Ikwuano" },
          { name: "Isiala Ngwa North" },
          { name: "Isiala Ngwa South" },
          { name: "Isuikwuato" },
          { name: "Obi Ngwa" },
          { name: "Ohafia" },
          { name: "Osisioma" },
          { name: "Ugwunagbo" },
          { name: "Ukwa East" },
          { name: "Ukwa West" },
          { name: "Umuahia North" },
          { name: "Umuahia South" },
          { name: "Umu Nneochi" }
        ]
      },
      {
        name: "Adamawa",
        lgas: [
          { name: "Demsa" },
          { name: "Fufore" },
          { name: "Ganye" },
          { name: "Girei" },
          { name: "Gombi" },
          { name: "Guyuk" },
          { name: "Hong" },
          { name: "Jada" },
          { name: "Lamurde" },
          { name: "Madagali" },
          { name: "Maiha" },
          { name: "Mayo Belwa" },
          { name: "Michika" },
          { name: "Mubi North" },
          { name: "Mubi South" },
          { name: "Numan" },
          { name: "Shelleng" },
          { name: "Song" },
          { name: "Toungo" },
          { name: "Yola North" },
          { name: "Yola South" }
        ]
      },
      {
        name: "Akwa Ibom",
        lgas: [
          { name: "Abak" },
          { name: "Eastern Obolo" },
          { name: "Eket" },
          { name: "Esit Eket" },
          { name: "Essien Udim" },
          { name: "Etim Ekpo" },
          { name: "Etinan" },
          { name: "Ibeno" },
          { name: "Ibesikpo Asutan" },
          { name: "Ibiono-Ibom" },
          { name: "Ika" },
          { name: "Ikono" },
          { name: "Ikot Abasi" },
          { name: "Ikot Ekpene" },
          { name: "Ini" },
          { name: "Itu" },
          { name: "Mbo" },
          { name: "Mkpat Enin" },
          { name: "Nsit Atai" },
          { name: "Nsit Ibom" },
          { name: "Nsit Ubium" },
          { name: "Obot Akara" },
          { name: "Okobo" },
          { name: "Onna" },
          { name: "Oron" },
          { name: "Oruk Anam" },
          { name: "Udung Uko" },
          { name: "Ukanafun" },
          { name: "Uruan" },
          { name: "Urue-Offong/Oruko" },
          { name: "Uyo" }
        ]
      },
     
      {
        name: "Ebonyi",
        lgas: [
          { name: "Abakaliki" },
          { name},]}],},],

          // africaCountries.ts

export interface LGAData {
  name: string;
}

export interface Subdivision {
  name: string;
  lgas?: LGAData[]; // Optional — only Nigeria uses it for now
}

export interface Country {
  country: string;
  subdivisions: Subdivision[];
}

export const africaCountries: Country[] = [
  {
    country: "Nigeria",
    subdivisions: [
      {
        name: "Abia",
        lgas: [
          { name: "Aba North" },
          { name: "Aba South" },
          { name: "Arochukwu" },
          { name: "Bende" },
          { name: "Ikwuano" },
          { name: "Isiala Ngwa North" },
          { name: "Isiala Ngwa South" },
          { name: "Isuikwuato" },
          { name: "Obi Ngwa" },
          { name: "Ohafia" },
          { name: "Osisioma" },
          { name: "Ugwunagbo" },
          { name: "Ukwa East" },
          { name: "Ukwa West" },
          { name: "Umuahia North" },
          { name: "Umuahia South" },
          { name: "Umu Nneochi" },
        ],
      },
      {
        name: "Adamawa",
        lgas: [
          { name: "Demsa" },
          { name: "Fufore" },
          { name: "Ganye" },
          { name: "Gayuk" },
          { name: "Gombi" },
          { name: "Grie" },
          { name: "Hong" },
          { name: "Jada" },
          { name: "Lamurde" },
          { name: "Madagali" },
          { name: "Maiha" },
          { name: "Mayo-Belwa" },
          { name: "Michika" },
          { name: "Mubi North" },
          { name: "Mubi South" },
          { name: "Numan" },
          { name: "Shelleng" },
          { name: "Song" },
          { name: "Toungo" },
          { name: "Yola North" },
          { name: "Yola South" },
        ],
      },
      {
        name: "Akwa Ibom",
        lgas: [
          { name: "Abak" },
          { name: "Eastern Obolo" },
          { name: "Eket" },
          { name: "Esit Eket" },
          { name: "Essien Udim" },
          { name: "Etim Ekpo" },
          { name: "Etinan" },
          { name: "Ibeno" },
          { name: "Ibesikpo Asutan" },
          { name: "Ibiono-Ibom" },
          { name: "Ika" },
          { name: "Ikono" },
          { name: "Ikot Abasi" },
          { name: "Ikot Ekpene" },
          { name: "Ini" },
          { name: "Itu" },
          { name: "Mbo" },
          { name: "Mkpat-Enin" },
          { name: "Nsit-Atai" },
          { name: "Nsit-Ibom" },
          { name: "Nsit-Ubium" },
          { name: "Obot Akara" },
          { name: "Okobo" },
          { name: "Onna" },
          { name: "Oron" },
          { name: "Oruk Anam" },
          { name: "Udung Uko" },
          { name: "Ukanafun" },
          { name: "Uruan" },
          { name: "Urue-Offong/Oruko" },
          { name: "Uyo" },
        ],
      },
       {
        name: "Anambra",
        lgas: [
          { name: "Aguata" },
          { name: "Anambra East" },
          { name: "Anambra West" },
          { name: "Anaocha" },
          { name: "Awka North" },
          { name: "Awka South" },
          { name: "Ayamelum" },
          { name: "Dunukofia" },
          { name: "Ekwusigo" },
          { name: "Idemili North" },
          { name: "Idemili South" },
          { name: "Ihiala" },
          { name: "Njikoka" },
          { name: "Nnewi North" },
          { name: "Nnewi South" },
          { name: "Ogbaru" },
          { name: "Onitsha North" },
          { name: "Onitsha South" },
          { name: "Orumba North" },
          { name: "Orumba South" },
          { name: "Oyi" }
        ]
      },
      {
        name: "Bauchi",
        lgas: [
          { name: "Alkaleri" },
          { name: "Bauchi" },
          { name: "Bogoro" },
          { name: "Damban" },
          { name: "Darazo" },
          { name: "Dass" },
          { name: "Ganjuwa" },
          { name: "Giade" },
          { name: "Itas/Gadau" },
          { name: "Jama'are" },
          { name: "Katagum" },
          { name: "Kirfi" },
          { name: "Misau" },
          { name: "Ningi" },
          { name: "Shira" },
          { name: "Tafawa Balewa" },
          { name: "Toro" },
          { name: "Warji" },
          { name: "Zaki" }
        ]
      },
      {
        name: "Bayelsa",
        lgas: [
          { name: "Brass" },
          { name: "Ekeremor" },
          { name: "Kolokuma/Opokuma" },
          { name: "Nembe" },
          { name: "Ogbia" },
          { name: "Sagbama" },
          { name: "Southern Ijaw" },
          { name: "Yenagoa" }
        ]
      },
      {
        name: "Benue",
        lgas: [
          { name: "Ado" },
          { name: "Agatu" },
          { name: "Apa" },
          { name: "Buruku" },
          { name: "Gboko" },
          { name: "Guma" },
          { name: "Gwer East" },
          { name: "Gwer West" },
          { name: "Katsina-Ala" },
          { name: "Konshisha" },
          { name: "Kwande" },
          { name: "Logo" },
          { name: "Makurdi" },
          { name: "Obi" },
          { name: "Ogbadibo" },
          { name: "Ohimini" },
          { name: "Oju" },
          { name: "Okpokwu" },
          { name: "Otukpo" },
          { name: "Tarka" },
          { name: "Ukum" },
          { name: "Ushongo" },
          { name: "Vandeikya" }
        ]
      },
      {
        name: "Borno",
        lgas: [
          { name: "Abadam" },
          { name: "Askira/Uba" },
          { name: "Bama" },
          { name: "Bayo" },
          { name: "Biu" },
          { name: "Chibok" },
          { name: "Damboa" },
          { name: "Dikwa" },
          { name: "Gubio" },
          { name: "Guzamala" },
          { name: "Gwoza" },
          { name: "Hawul" },
          { name: "Jere" },
          { name: "Kaga" },
          { name: "Kala/Balge" },
          { name: "Konduga" },
          { name: "Kukawa" },
          { name: "Kwaya Kusar" },
          { name: "Mafa" },
          { name: "Magumeri" },
          { name: "Maiduguri" },
          { name: "Marte" },
          { name: "Mobbar" },
          { name: "Monguno" },
          { name: "Ngala" },
          { name: "Nganzai" },
          { name: "Shani" }
        ]
      },
      {
        name: "Cross River",
        lgas: [
          { name: "Abi" },
          { name: "Akamkpa" },
          { name: "Akpabuyo" },
          { name: "Bakassi" },
          { name: "Bekwarra" },
          { name: "Biase" },
          { name: "Boki" },
          { name: "Calabar Municipal" },
          { name: "Calabar South" },
          { name: "Etung" },
          { name: "Ikom" },
          { name: "Obanliku" },
          { name: "Obubra" },
          { name: "Obudu" },
          { name: "Ogoja" },
          { name: "Yala" }
        ]
      },
      {
        name: "Delta",
        lgas: [
          { name: "Aniocha North" },
          { name: "Aniocha South" },
          { name: "Bomadi" },
          { name: "Burutu" },
          { name: "Ethiope East" },
          { name: "Ethiope West" },
          { name: "Ika North East" },
          { name: "Ika South" },
          { name: "Isoko North" },
          { name: "Isoko South" },
          { name: "Ndokwa East" },
          { name: "Ndokwa West" },
          { name: "Okpe" },
          { name: "Oshimili North" },
          { name: "Oshimili South" },
          { name: "Patani" },
          { name: "Sapele" },
          { name: "Udu" },
          { name: "Ughelli North" },
          { name: "Ughelli South" },
          { name: "Ukwuani" },
          { name: "Uvwie" },
          { name: "Warri North" },
          { name: "Warri South" },
          { name: "Warri South West" }
        ]
      },
       {
        name: "Ebonyi",
        lgas: [
          { name: "Abakaliki" },
          { name: "Afikpo North" },
          { name: "Afikpo South (Edda)" },
          { name: "Ebonyi" },
          { name: "Ezza North" },
          { name: "Ezza South" },
          { name: "Ikwo" },
          { name: "Ishielu" },
          { name: "Ivo" },
          { name: "Izzi" },
          { name: "Ohaozara" },
          { name: "Ohaukwu" },
          { name: "Onicha" },
        ]
      },
      {
        name: "Edo",
        lgas: [
          { name: "Akoko Edo" },
          { name: "Egor" },
          { name: "Esan Central" },
          { name: "Esan North-East" },
          { name: "Esan South-East" },
          { name: "Esan West" },
          { name: "Etsako Central" },
          { name: "Etsako East" },
          { name: "Etsako West", },
          { name: "Igueben" },
          { name: "Ikpoba-Okha" },
          { name: "Oredo" },
          { name: "Orhionmwon" },
          { name: "Ovia North-East" },
          { name: "Ovia South-West" },
          { name: "Owan East" },
          { name: "Owan West" },
          { name: "Uhunmwonde" },
        ]
      },
      {
        name: "Ekiti",
        lgas: [
          { name: "Ado Ekiti" },
          { name: "Ekiti East" },
          { name: "Ekiti South-West" },
          { name: "Ekiti West" },
          { name: "Emure/Ise/Orun" },
          { name: "Gbonyin" },
          { name: "Ido/Osi" },
          { name: "Ilejemeje" },
          { name: "Irepodun/Ifelodun" },
          { name: "Ise/Orun" },
          { name: "Moba" },
          { name: "Oye" }
        ]
      },
      //states from here are not benue  { name: "" },
      {
        name: "Benue",
        lgas: [
          { name: "Ado" },
          { name: "Agatu" },
          { name: "Apa" },
          { name: "Buruku" },
          { name: "Gboko" },
          { name: "Guma" },
          { name: "Gwer East" },
          { name: "Gwer West" },
          { name: "Katsina-Ala" },
          { name: "Konshisha" },
          { name: "Kwande" },
          { name: "Logo" },
          { name: "Makurdi" },
          { name: "Obi" },
          { name: "Ogbadibo" },
          { name: "Ohimini" },
          { name: "Oju" },
          { name: "Okpokwu" },
          { name: "Otukpo" },
          { name: "Tarka" },
          { name: "Ukum" },
          { name: "Ushongo" },
          { name: "Vandeikya" }
        ]
      },
      {
        name: "Borno",
        lgas: [
          { name: "Abadam" },
          { name: "Askira/Uba" },
          { name: "Bama" },
          { name: "Bayo" },
          { name: "Biu" },
          { name: "Chibok" },
          { name: "Damboa" },
          { name: "Dikwa" },
          { name: "Gubio" },
          { name: "Guzamala" },
          { name: "Gwoza" },
          { name: "Hawul" },
          { name: "Jere" },
          { name: "Kaga" },
          { name: "Kala/Balge" },
          { name: "Konduga" },
          { name: "Kukawa" },
          { name: "Kwaya Kusar" },
          { name: "Mafa" },
          { name: "Magumeri" },
          { name: "Maiduguri" },
          { name: "Marte" },
          { name: "Mobbar" },
          { name: "Monguno" },
          { name: "Ngala" },
          { name: "Nganzai" },
          { name: "Shani" }
        ]
      },
      {
        name: "Cross River",
        lgas: [
          { name: "Abi" },
          { name: "Akamkpa" },
          { name: "Akpabuyo" },
          { name: "Bakassi" },
          { name: "Bekwarra" },
          { name: "Biase" },
          { name: "Boki" },
          { name: "Calabar Municipal" },
          { name: "Calabar South" },
          { name: "Etung" },
          { name: "Ikom" },
          { name: "Obanliku" },
          { name: "Obubra" },
          { name: "Obudu" },
          { name: "Ogoja" },
          { name: "Yala" }
        ]
      },
      {
        name: "Delta",
        lgas: [
          { name: "Aniocha North" },
          { name: "Aniocha South" },
          { name: "Bomadi" },
          { name: "Burutu" },
          { name: "Ethiope East" },
          { name: "Ethiope West" },
          { name: "Ika North East" },
          { name: "Ika South" },
          { name: "Isoko North" },
          { name: "Isoko South" },
          { name: "Ndokwa East" },
          { name: "Ndokwa West" },
          { name: "Okpe" },
          { name: "Oshimili North" },
          { name: "Oshimili South" },
          { name: "Patani" },
          { name: "Sapele" },
          { name: "Udu" },
          { name: "Ughelli North" },
          { name: "Ughelli South" },
          { name: "Ukwuani" },
          { name: "Uvwie" },
          { name: "Warri North" },
          { name: "Warri South" },
          { name: "Warri South West" }
        ]
      },
       {
        name: "Anambra",
        lgas: [
          { name: "Aguata" },
          { name: "Anambra East" },
          { name: "Anambra West" },
          { name: "Anaocha" },
          { name: "Awka North" },
          { name: "Awka South" },
          { name: "Ayamelum" },
          { name: "Dunukofia" },
          { name: "Ekwusigo" },
          { name: "Idemili North" },
          { name: "Idemili South" },
          { name: "Ihiala" },
          { name: "Njikoka" },
          { name: "Nnewi North" },
          { name: "Nnewi South" },
          { name: "Ogbaru" },
          { name: "Onitsha North" },
          { name: "Onitsha South" },
          { name: "Orumba North" },
          { name: "Orumba South" },
          { name: "Oyi" }
        ]
      },
      {
        name: "Bauchi",
        lgas: [
          { name: "Alkaleri" },
          { name: "Bauchi" },
          { name: "Bogoro" },
          { name: "Damban" },
          { name: "Darazo" },
          { name: "Dass" },
          { name: "Ganjuwa" },
          { name: "Giade" },
          { name: "Itas/Gadau" },
          { name: "Jama'are" },
          { name: "Katagum" },
          { name: "Kirfi" },
          { name: "Misau" },
          { name: "Ningi" },
          { name: "Shira" },
          { name: "Tafawa Balewa" },
          { name: "Toro" },
          { name: "Warji" },
          { name: "Zaki" }
        ]
      },
      {
        name: "Bayelsa",
        lgas: [
          { name: "Brass" },
          { name: "Ekeremor" },
          { name: "Kolokuma/Opokuma" },
          { name: "Nembe" },
          { name: "Ogbia" },
          { name: "Sagbama" },
          { name: "Southern Ijaw" },
          { name: "Yenagoa" }
        ]
      },
      {
        name: "Benue",
        lgas: [
          { name: "Ado" },
          { name: "Agatu" },
          { name: "Apa" },
          { name: "Buruku" },
          { name: "Gboko" },
          { name: "Guma" },
          { name: "Gwer East" },
          { name: "Gwer West" },
          { name: "Katsina-Ala" },
          { name: "Konshisha" },
          { name: "Kwande" },
          { name: "Logo" },
          { name: "Makurdi" },
          { name: "Obi" },
          { name: "Ogbadibo" },
          { name: "Ohimini" },
          { name: "Oju" },
          { name: "Okpokwu" },
          { name: "Otukpo" },
          { name: "Tarka" },
          { name: "Ukum" },
          { name: "Ushongo" },
          { name: "Vandeikya" }
        ]
      },
      {
        name: "Borno",
        lgas: [
          { name: "Abadam" },
          { name: "Askira/Uba" },
          { name: "Bama" },
          { name: "Bayo" },
          { name: "Biu" },
          { name: "Chibok" },
          { name: "Damboa" },
          { name: "Dikwa" },
          { name: "Gubio" },
          { name: "Guzamala" },
          { name: "Gwoza" },
          { name: "Hawul" },
          { name: "Jere" },
          { name: "Kaga" },
          { name: "Kala/Balge" },
          { name: "Konduga" },
          { name: "Kukawa" },
          { name: "Kwaya Kusar" },
          { name: "Mafa" },
          { name: "Magumeri" },
          { name: "Maiduguri" },
          { name: "Marte" },
          { name: "Mobbar" },
          { name: "Monguno" },
          { name: "Ngala" },
          { name: "Nganzai" },
          { name: "Shani" }
        ]
      },
      {
        name: "Cross River",
        lgas: [
          { name: "Abi" },
          { name: "Akamkpa" },
          { name: "Akpabuyo" },
          { name: "Bakassi" },
          { name: "Bekwarra" },
          { name: "Biase" },
          { name: "Boki" },
          { name: "Calabar Municipal" },
          { name: "Calabar South" },
          { name: "Etung" },
          { name: "Ikom" },
          { name: "Obanliku" },
          { name: "Obubra" },
          { name: "Obudu" },
          { name: "Ogoja" },
          { name: "Yala" }
        ]
      },
      {
        name: "Delta",
        lgas: [
          { name: "Aniocha North" },
          { name: "Aniocha South" },
          { name: "Bomadi" },
          { name: "Burutu" },
          { name: "Ethiope East" },
          { name: "Ethiope West" },
          { name: "Ika North East" },
          { name: "Ika South" },
          { name: "Isoko North" },
          { name: "Isoko South" },
          { name: "Ndokwa East" },
          { name: "Ndokwa West" },
          { name: "Okpe" },
          { name: "Oshimili North" },
          { name: "Oshimili South" },
          { name: "Patani" },
          { name: "Sapele" },
          { name: "Udu" },
          { name: "Ughelli North" },
          { name: "Ughelli South" },
          { name: "Ukwuani" },
          { name: "Uvwie" },
          { name: "Warri North" },
          { name: "Warri South" },
          { name: "Warri South West" }
        ]
      },
       {
        name: "Anambra",
        lgas: [
          { name: "Aguata" },
          { name: "Anambra East" },
          { name: "Anambra West" },
          { name: "Anaocha" },
          { name: "Awka North" },
          { name: "Awka South" },
          { name: "Ayamelum" },
          { name: "Dunukofia" },
          { name: "Ekwusigo" },
          { name: "Idemili North" },
          { name: "Idemili South" },
          { name: "Ihiala" },
          { name: "Njikoka" },
          { name: "Nnewi North" },
          { name: "Nnewi South" },
          { name: "Ogbaru" },
          { name: "Onitsha North" },
          { name: "Onitsha South" },
          { name: "Orumba North" },
          { name: "Orumba South" },
          { name: "Oyi" }
        ]
      },
      {
        name: "Bauchi",
        lgas: [
          { name: "Alkaleri" },
          { name: "Bauchi" },
          { name: "Bogoro" },
          { name: "Damban" },
          { name: "Darazo" },
          { name: "Dass" },
          { name: "Ganjuwa" },
          { name: "Giade" },
          { name: "Itas/Gadau" },
          { name: "Jama'are" },
          { name: "Katagum" },
          { name: "Kirfi" },
          { name: "Misau" },
          { name: "Ningi" },
          { name: "Shira" },
          { name: "Tafawa Balewa" },
          { name: "Toro" },
          { name: "Warji" },
          { name: "Zaki" }
        ]
      },
      {
        name: "Bayelsa",
        lgas: [
          { name: "Brass" },
          { name: "Ekeremor" },
          { name: "Kolokuma/Opokuma" },
          { name: "Nembe" },
          { name: "Ogbia" },
          { name: "Sagbama" },
          { name: "Southern Ijaw" },
          { name: "Yenagoa" }
        ]
      },
      {
        name: "Benue",
        lgas: [
          { name: "Ado" },
          { name: "Agatu" },
          { name: "Apa" },
          { name: "Buruku" },
          { name: "Gboko" },
          { name: "Guma" },
          { name: "Gwer East" },
          { name: "Gwer West" },
          { name: "Katsina-Ala" },
          { name: "Konshisha" },
          { name: "Kwande" },
          { name: "Logo" },
          { name: "Makurdi" },
          { name: "Obi" },
          { name: "Ogbadibo" },
          { name: "Ohimini" },
          { name: "Oju" },
          { name: "Okpokwu" },
          { name: "Otukpo" },
          { name: "Tarka" },
          { name: "Ukum" },
          { name: "Ushongo" },
          { name: "Vandeikya" }
        ]
      },
      {
        name: "Borno",
        lgas: [
          { name: "Abadam" },
          { name: "Askira/Uba" },
          { name: "Bama" },
          { name: "Bayo" },
          { name: "Biu" },
          { name: "Chibok" },
          { name: "Damboa" },
          { name: "Dikwa" },
          { name: "Gubio" },
          { name: "Guzamala" },
          { name: "Gwoza" },
          { name: "Hawul" },
          { name: "Jere" },
          { name: "Kaga" },
          { name: "Kala/Balge" },
          { name: "Konduga" },
          { name: "Kukawa" },
          { name: "Kwaya Kusar" },
          { name: "Mafa" },
          { name: "Magumeri" },
          { name: "Maiduguri" },
          { name: "Marte" },
          { name: "Mobbar" },
          { name: "Monguno" },
          { name: "Ngala" },
          { name: "Nganzai" },
          { name: "Shani" }
        ]
      },
      {
        name: "Cross River",
        lgas: [
          { name: "Abi" },
          { name: "Akamkpa" },
          { name: "Akpabuyo" },
          { name: "Bakassi" },
          { name: "Bekwarra" },
          { name: "Biase" },
          { name: "Boki" },
          { name: "Calabar Municipal" },
          { name: "Calabar South" },
          { name: "Etung" },
          { name: "Ikom" },
          { name: "Obanliku" },
          { name: "Obubra" },
          { name: "Obudu" },
          { name: "Ogoja" },
          { name: "Yala" }
        ]
      },
      {
        name: "Delta",
        lgas: [
          { name: "Aniocha North" },
          { name: "Aniocha South" },
          { name: "Bomadi" },
          { name: "Burutu" },
          { name: "Ethiope East" },
          { name: "Ethiope West" },
          { name: "Ika North East" },
          { name: "Ika South" },
          { name: "Isoko North" },
          { name: "Isoko South" },
          { name: "Ndokwa East" },
          { name: "Ndokwa West" },
          { name: "Okpe" },
          { name: "Oshimili North" },
          { name: "Oshimili South" },
          { name: "Patani" },
          { name: "Sapele" },
          { name: "Udu" },
          { name: "Ughelli North" },
          { name: "Ughelli South" },
          { name: "Ukwuani" },
          { name: "Uvwie" },
          { name: "Warri North" },
          { name: "Warri South" },
          { name: "Warri South West" }
        ]
      },
      // ... continue all 36 states + FCT with their LGAs
    ],
  },
  {
    country: "Egypt",
    subdivisions: [
      { name: "Cairo" },
      { name: "Giza" },
      { name: "Alexandria" },
      { name: "Dakahlia" },
      { name: "Sharqia" },
      { name: "Qalyubia" },
      { name: "Kafr El Sheikh" },
      { name: "Gharbia" },
      { name: "Monufia" },
      { name: "Beheira" },
      { name: "Damietta" },
      { name: "Port Said" },
      { name: "Suez" },
      { name: "Ismailia" },
      { name: "Beni Suef" },
      { name: "Faiyum" },
      { name: "Minya" },
      { name: "Asyut" },
      { name: "Sohag" },
      { name: "Qena" },
      { name: "Luxor" },
      { name: "Aswan" },
      { name: "Red Sea" },
      { name: "New Valley" },
      { name: "Matruh" },
      { name: "North Sinai" },
      { name: "South Sinai" },
    ],
  },
  {
    country: "South Africa",
    subdivisions: [
      { name: "Eastern Cape" },
      { name: "Free State" },
      { name: "Gauteng" },
      { name: "KwaZulu-Natal" },
      { name: "Limpopo" },
      { name: "Mpumalanga" },
      { name: "North West" },
      { name: "Northern Cape" },
      { name: "Western Cape" },
    ],
  },
  {
    country: "Kenya",
    subdivisions: [
      { name: "Nairobi" },
      { name: "Mombasa" },
      { name: "Kisumu" },
      { name: "Nakuru" },
      { name: "Kiambu" },
      { name: "Machakos" },
      { name: "Uasin Gishu" },
      { name: "Kakamega" },
      { name: "Kericho" },
      { name: "Nyeri" },
    ],
  },
  {
    country: "Ghana",
    subdivisions: [
      { name: "Greater Accra" },
      { name: "Ashanti" },
      { name: "Eastern" },
      { name: "Western" },
      { name: "Central" },
      { name: "Volta" },
      { name: "Northern" },
      { name: "Upper East" },
      { name: "Upper West" },
    ],
  },
  {
    country: "Ethiopia",
    subdivisions: [
      { name: "Addis Ababa" },
      { name: "Amhara" },
      { name: "Oromia" },
      { name: "Somali" },
      { name: "Tigray" },
      { name: "Sidama" },
      { name: "SNNPR" },
      { name: "Harari" },
      { name: "Dire Dawa" },
    ],
  },
  {
    country: "Morocco",
    subdivisions: [
      { name: "Casablanca-Settat" },
      { name: "Rabat-Salé-Kénitra" },
      { name: "Fès-Meknès" },
      { name: "Marrakech-Safi" },
      { name: "Oriental" },
      { name: "Souss-Massa" },
    ],
  },
  {
    country: "Algeria",
    subdivisions: [
      { name: "Algiers" },
      { name: "Oran" },
      { name: "Constantine" },
      { name: "Annaba" },
      { name: "Blida" },
      { name: "Tlemcen" },
      { name: "Tizi Ouzou" },
    ],
  },
  {
    country: "Uganda",
    subdivisions: [
      { name: "Central" },
      { name: "Eastern" },
      { name: "Northern" },
      { name: "Western" },
      { name: "Kampala" },
    ],
  },
  {
    country: "Tanzania",
    subdivisions: [
      { name: "Dar es Salaam" },
      { name: "Dodoma" },
      { name: "Arusha" },
      { name: "Mwanza" },
      { name: "Mbeya" },
      { name: "Tanga" },
      { name: "Morogoro" },
      { name: "Kilimanjaro" },
      { name: "Ruvuma" },
      { name: "Zanzibar" },
    ],
  },
];
